### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by thumorten** [thumorten/markdown-portfolio#2]
- [x] Additional markup is supported, including @mentions, #referencess, [links](url), **emphasis**
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.

**Comment by thumorten** [comment]
s
